fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
showpage:
    path: /showpage
    controller: App\Controller\ShowpageController::index
